# Spam Classifier
## Assignment Preamble
Please ensure you carefully read all of the details and instructions on the assignment page, this section, and the rest of the notebook. If anything is unclear at any time please post on the forum or ask a tutor well in advance of the assignment deadline.

In addition to all of the instructions in the body of the assignment below, you must also follow the following technical instructions for all assignments in this unit. *Failure to do so may result in a grade of zero.*
* [At the bottom of the page](#Submission-Test) is some code which checks you meet the submission requirements. You **must** ensure that this runs correctly before submission.
* Do not modify or delete any of the cells that are marked as test cells, even if they appear to be empty.
* Do not duplicate any cells in the notebook – this can break the marking script. Instead, insert a new cell (e.g. from the menu) and copy across any contents as necessary.

Remember to save and backup your work regularly, and double-check you are submitting the correct version.

This notebook is the primary reference for your submission. You may write code in separate `.py` files but it must be clearly imported into the notebook so that it runs without needing to reference those files, and you must explain clearly what functionality is contained in those files (through comments, markdown cells, etc).

As always, **the work you submit for this assignment must be entirely your own.** Do not copy or work with other students. Do not copy answers that you find online. These assignments are designed to help improve your understanding first and foremost – the process of doing the assignment is part of *learning*. They are also used to assess your ability, and so you must uphold academic integrity. Submitting plagiarised work risks your entire place on your degree.

**The pass mark for this assignment is 40%.** We expect that students, on average, will be able to produce a submission which gets a mark between 50-70% within the normal workload allocation for the unit, but this will vary depending on individual backgrounds. Please ask for help if you are struggling.

## Getting Started
Spam refers to unwanted email, often in the form of advertisements. In the literature, an email that is **not** spam is called *ham*. Most email providers offer automatic spam filtering, where spam emails will be moved to a separate inbox based on their contents. Of course this requires being able to scan an email and determine whether it is spam or ham, a classification problem. This is the subject of this assignment.

This assignment has two parts. Each part is worth 50% of the overall grade for this assignment.

For part one you will write a supervised learning based classifier to determine whether a given email is spam or ham. You must write and submit the code in this notebook. The training data is provided for you. You may use any classification method. Marks will be awarded primarily based on the accuracy of your classifier on unseen test data, but there are also marks for estimating how accurate you think your classifier will be.

In part two you will produce a short video explaining your implementation, any decisions or extensions you made, and what parameter values you used. This part is explained in more detail on the assignment page. The video file must be submitted with your assignment.

### Choice of Algorithm
While the classification method is a completely free choice, the assignment folder includes [a separate notebook file](data/naivebayes.ipynb) which can help you implement a Naïve Bayes solution. If you do use this notebook, you are still responsible for porting your code into *this* notebook for submission. A good implementation should give a high  enough accuracy to get a good grade on this section (50-70%).

You could also consider a k-nearest neighbour algorithm, but this may be less accurate. Logistic regression is another option that you may wish to consider.

If you are looking to go beyond the scope of the unit, you might be interested in building something more advanced, like an artificial neural network. This is possible just using `numpy`, but will require significant self-directed learning. *Extensions like this are left unguided and are not factored into the unit workload estimates.*

**Note:** you may use helper functions in libraries like `numpy` or `scipy`, but you **must not** import code which builds entire models for you. This includes but is not limited to use of libraries like `scikit-learn`, `tensorflow`, or `pytorch` – there will be plenty of opportunities for these libraries in later units. The point of this assignment is to understand code the actual algorithm yourself. ***If you are in any doubt about any particular library or function please ask a tutor.*** Submissions which ignore this will receive penalties or even zero marks.

If you choose to implement more than one algorithm, please feel free to include your code and talk about it in part two (your video presentation), but only the code in this notebook will be used in the automated testing.

## Training Data
The training data is described below and has 1000 rows. There is also a 500 row set of test data. These are functionally identical to the training data, they are just in a separate csv file to encourage you to split out your training and test data. You should consider how to best make use of all available data without overfitting, and to help produce an unbiased estimate for your classifier's accuracy.

The cell below loads the training data into a variable called `training_spam`.

In [1]:
import numpy as np

training_spam = np.loadtxt(open("data/training_spam.csv"), delimiter=",").astype(np.int)
print("Shape of the spam training data set:", training_spam.shape)
print(training_spam)

Shape of the spam training data set: (1000, 55)
[[1 0 0 ... 0 0 0]
 [0 0 1 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [1 1 1 ... 1 1 0]
 [1 0 0 ... 1 1 1]]


<ipython-input-1-9b07313e2dc5>:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  training_spam = np.loadtxt(open("data/training_spam.csv"), delimiter=",").astype(np.int)


Your training set consists of 1000 rows and 55 columns. Each row corresponds to one email message. The first column is the _response_ variable and describes whether a message is spam `1` or ham `0`. The remaining 54 columns are _features_ that you will use to build a classifier. These features correspond to 54 different keywords (such as "money", "free", and "receive") and special characters (such as ":", "!", and "$"). A feature has the value `1` if the keyword appears in the message and `0` otherwise.

As mentioned there is also a 500 row set of *test data*. It contains the same 55 columns.

In [2]:
testing_spam = np.loadtxt(open("data/testing_spam.csv"), delimiter=",").astype(np.int)
print("Shape of the spam testing data set:", testing_spam.shape)
print(testing_spam)

Shape of the spam testing data set: (500, 55)
[[1 0 0 ... 1 1 1]
 [1 1 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]]


<ipython-input-2-7b09f440222b>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  testing_spam = np.loadtxt(open("data/testing_spam.csv"), delimiter=",").astype(np.int)


## Part One
Write all of the code for your classifier below this cell. There is some very rough skeleton code in the cell directly below. You may insert more cells below this if you wish, but you must not duplicate any cells as this can break the grading script.

### Submission Requirements
Your code must provide a variable with the name `classifier`. This object must have a method called `predict` which takes input data and returns class predictions. The input will be a single $n \times 54$ numpy array, your classifier should return a numpy array of length $n$ with classifications. There is a demo in the cell below, and a test you can run before submitting to check your code is working correctly.

Your code must run on our test machine in under 30 seconds. If you wish to train a more complicated model (e.g. neural network) which will take longer, you are welcome to save the model's weights as a file and then load these in the cell below so we can test it. You must include the code which computes the original weights, but this must not run when we run the notebook – comment out the code which actually executes the routine and make sure it is clear what we need to change to get it to run. Remember that we will be testing your final classifier on additional hidden data.

In [3]:
import math
import numpy
class SpamClassifier:
    def __init__(self):
        pass
        
    def train(self, training_data):
        self.k = training_data.shape[1] - 1
        self.log_class_priors = self.estimate_log_class_priors(training_data)
        self.log_class_conditional_likelihoods = self.estimate_log_class_conditional_likelihoods(training_data)
        
    def estimate_log_class_priors(self, training_data):
        # Iterates through all the training data, to determine p(C=0) p(C=1)
        count_zero = 0
        count_one = 0
        for i, element in enumerate(training_data):
            if training_data[i][0] == 0:
                count_zero += 1
            else:
                count_one += 1
        # Calculates percentages p(C=0) p(C=1)
        p_count_one = count_one / len(training_data)
        p_count_zero = count_zero / len(training_data)
        # Calculate the log values of p(C=0) p(C=1) and returns them
        spam_log_p_one = math.log10(p_count_one)
        ham_log_p_zero = math.log10(p_count_zero)
        return np.array([spam_log_p_one, ham_log_p_zero])
    
    def estimate_log_class_conditional_likelihoods(self, training_data, alpha=1.0):
        # Calculates numpy array with only spam rows, or only ham rows
        spam_arr = training_data[training_data[:, 0] == 1]
        ham_arr  = training_data[training_data[:, 0] == 0]
        # Calculates nc for both classes, spam and ham
        spam_nc = spam_arr[:, 1:].sum()
        ham_nc = ham_arr[:, 1:].sum()
        # Calculates 𝜃c,w for both classes, spam and ham
        theta_spam = spam_arr[:, 1:].sum(axis=0)
        theta_ham = ham_arr[:, 1:].sum(axis=0)
        # Combines and returns results
        theta_spam = (theta_spam + alpha) / (spam_nc + (alpha * self.k))
        theta_spam = np.log10(theta_spam)
        theta_ham = (theta_ham + alpha) / (ham_nc + (alpha * self.k))
        theta_ham = np.log10(theta_ham)
        return np.array([theta_spam, theta_ham])
        
        
    def predict(self, data):
        spam_predict = self.log_class_priors[0] + np.sum(data * self.log_class_conditional_likelihoods[0], axis=1)
        ham_predict = self.log_class_priors[1] + np.sum(data * self.log_class_conditional_likelihoods[1], axis=1)
        class_predictions = np.where(spam_predict > ham_predict, 1, 0)
        return class_predictions
    
    def predict_for_ensemble(self, data):
        # Returns true value obtained and not 0 or 1, to compare with other machines
        spam_predict = self.log_class_priors[0] + np.sum(data * self.log_class_conditional_likelihoods[0], axis=1)
        ham_predict = self.log_class_priors[1] + np.sum(data * self.log_class_conditional_likelihoods[1], axis=1)
        return [spam_predict, ham_predict]
    

class EnsembleClassifier:
    def __init__(self, *classifiers):
        self.classifiers = classifiers
    
    def predict(self, data):
        sum_spam = 0
        sum_ham = 0
        count = 0
        for classifier in self.classifiers:
            prediction = classifier.predict_for_ensemble(data)
            sum_spam += prediction[0]
            sum_ham += prediction[1]
            count += 1
        mean_spam = sum_spam / count
        mean_ham = sum_ham / count
        # Returns final result as mean of all individual classifiers
        return np.where(mean_spam > mean_ham, 1, 0)
    

def create_classifier(training_spam):
    classifier = SpamClassifier()
    classifier.train(training_spam)
    return classifier

def k_fold_cross_validation(training_spam, p, e):
    # Shuffle dataset
    total_count = training_spam.shape[0]
    shuffle = np.random.permutation(total_count)
    data_shuffled = training_spam[shuffle]
    # Splits dataset into 5 subsets for validations
    data_split = np.array_split(data_shuffled, 5)
    
    # Calculate the final prediction as a mean of all 5 validation rounds
    total_validation_accuracy = 0
    total_testing_accuracy = 0
    for validation_round, testing_set in enumerate(data_split):
        training_set = [x for i, x in enumerate(data_split) if i!=validation_round]
        training_set = np.concatenate(training_set)
        # Parameter e determines, how many individual classifiers will be used in ensemble
        classifier_list = []
        for i in range(e):
            classifier_list.append(create_classifier(random_training_subset(training_set, p)))
        classifier = EnsembleClassifier(*classifier_list)
        # Makes predictions on validation and testing set
        validation_prediction = classifier.predict(testing_set[:, 1:])
        testing_prediction = classifier.predict(test_data)
        validation_labels = testing_set[:, 0]
        validation_accuracy = np.count_nonzero(validation_prediction == validation_labels)/validation_labels.shape[0]
        testing_accuracy =  np.count_nonzero(testing_prediction == test_labels)/test_labels.shape[0]
        total_validation_accuracy += validation_accuracy
        total_testing_accuracy += testing_accuracy
    total_validation_accuracy = total_validation_accuracy / 5
    total_testing_accuracy = total_testing_accuracy / 5
    return [total_validation_accuracy, total_testing_accuracy]
        
def random_training_subset(training_set, p):
    training_indexes = np.random.choice(training_set.shape[1], int(p*training_set.shape[1]), replace=True)
    return training_set[training_indexes, :]
    

# Parameter Testing...
testing_spam = np.loadtxt(open("data/testing_spam.csv"), delimiter=",").astype(np.int)
test_data = testing_spam[:, 1:]
test_labels = testing_spam[:, 0]

parameter_testing = False
if parameter_testing:
    # Saves best predictions and parameters used to make those predictions
    best_validation_prediction = [0, 0, 0]
    best_testing_prediction = [0, 0, 0]
    for p in np.linspace(0.7, 0.99, 50):
        for e in range(1, 10, 1):
            prediction_total = [0, 0]
            for i in range(10):
                predictions = k_fold_cross_validation(training_spam, p, e=5)
                prediction_total[0] += predictions[0]
                prediction_total[1] += predictions[1]
            prediction_total[0] = prediction_total[0] / 10
            prediction_total[1] = prediction_total[1] / 10
            print(f"Parameters used were: p={p: 0.3f} and e={e}")
            print(f"The accuracy mean results on the validation set where: {prediction_total[0]}")
            print(f"The accuracy mean results on the test set where: {prediction_total[1]}")
            print("-" * 20)
            if prediction_total[0] > best_validation_prediction[0]:
                best_validation_prediction[0] = prediction_total[0]
                best_validation_prediction[1] = p
                best_validation_prediction[2] = e
            if prediction_total[1] > best_testing_prediction[0]:
                best_testing_prediction[0] = prediction_total[1]
                best_testing_prediction[1] = p
                best_testing_prediction[2] = e
            
            
    print(f"The best validation performance of {best_validation_prediction[0]} was reached with p={best_validation_prediction[1]} and e={best_validation_prediction[2]}")
    print(f"The best testing performance of {best_testing_prediction[0]} was reached with p={best_testing_prediction[1]} and e={best_testing_prediction[2]}")        
# Result of Parameter Testing:
# The best validation performance of 0.889 was reached with p=0.8361224489795918 and e=3
# The best testing performance of 0.89672 was reached with p=0.8361224489795918 and e=3
    
# Normal Naive Bayes Classifier
classifier = create_classifier(training_spam) # Result on Test Data: 0.8623
results_classifier = [0, 0]
if parameter_testing:
    for i in range(10):
        k_fold_cross_results = k_fold_cross_validation(training_spam, p=1, e=1)
        results_classifier[0] += k_fold_cross_results[0]
        results_classifier[1] += k_fold_cross_results[1]
    results_classifier[0] = results_classifier[0] / 10
    results_classifier[1] = results_classifier[1] / 10
    print(f"Performance of normal Classifier (p=1, e=1): {results_classifier}")

# Ensemble Classifier
classifier_list = []
for e in range(3):
    classifier_list.append(create_classifier(random_training_subset(training_spam, 0.8361)))
classifier = EnsembleClassifier(*classifier_list)

<ipython-input-3-564a433f6949>:121: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  testing_spam = np.loadtxt(open("data/testing_spam.csv"), delimiter=",").astype(np.int)


### Accuracy Estimate
In the cell below there is a function called `my_accuracy_estimate()` which returns `0.5`. Before you submit the assignment, write your best guess for the accuracy of your classifier into this function, as a percentage between `0` and `1`. So if you think you will get 80% of inputs correct, return the value `0.8`. This will form a small part of the marking criteria for the assignment, to encourage you to test your own code.

In [5]:
def my_accuracy_estimate():
    return 0.89

Write all of the code for your classifier above this cell.

### Testing Details
Your classifier will be tested against some hidden data from the same source as the original. The accuracy (percentage of classifications correct) will be calculated, then benchmarked against common methods. At the very high end of the grading scale, your accuracy will also be compared to the best submissions from other students (in your own cohort and others!). Your estimate from the cell above will also factor in, and you will be rewarded for being close to your actual accuracy (overestimates and underestimates will be treated the same).

#### Test Cell
The following code will run your classifier against the provided test data. To enable it, set the constant `SKIP_TESTS` to `False`.

The original skeleton code above classifies every row as ham, but once you have written your own classifier you can run this cell again to test it. So long as your code sets up a variable called `classifier` with a method called `predict`, the test code will be able to run. 

Of course you may wish to test your classifier in additional ways, but you *must* ensure this version still runs before submitting.

**IMPORTANT**: you must set `SKIP_TESTS` back to `True` before submitting this file!

In [6]:
SKIP_TESTS = True

if not SKIP_TESTS:
    testing_spam = np.loadtxt(open("data/testing_spam.csv"), delimiter=",").astype(np.int)
    test_data = testing_spam[:, 1:]
    test_labels = testing_spam[:, 0]

    predictions = classifier.predict(test_data)
    accuracy = np.count_nonzero(predictions == test_labels)/test_labels.shape[0]
    print(f"Accuracy on test data is: {accuracy}")

In [7]:
import sys
import pathlib

fail = False;

if not SKIP_TESTS:
    fail = True;
    print("You must set the SKIP_TESTS constant to True in the cell above.")
    
p3 = pathlib.Path('./spamclassifier.ipynb')
if not p3.is_file():
    fail = True
    print("This notebook file must be named spamclassifier.ipynb")
    
if "create_classifier" not in dir():
    fail = True;
    print("You must include a function called create_classifier.")

if "my_accuracy_estimate" not in dir():
    fail = True;
    print("You must include a function called my_accuracy_estimate.")
else:
    if my_accuracy_estimate() == 0.5:
        print("Warning:")
        print("You do not seem to have provided an accuracy estimate, it is set to 0.5.")
        print("This is the actually the worst possible accuracy – if your classifier")
        print("got 0.1 then it could invert its results to get 0.9!")
    
print("INFO: Make sure you follow the instructions on the assignment page to submit your video.")
print("Failing to include this could result in an overall grade of zero for both parts.")
print()

if fail:
    sys.stderr.write("Your submission is not ready! Please read and follow the instructions above.")
else:
    print("All checks passed. When you are ready to submit, upload the notebook and readme file to the")
    print("assignment page, without changing any filenames.")
    print()
    print("If you need to submit multiple files, you can archive them in a .zip file. (No other format.)")

INFO: Make sure you follow the instructions on the assignment page to submit your video.
Failing to include this could result in an overall grade of zero for both parts.

All checks passed. When you are ready to submit, upload the notebook and readme file to the
assignment page, without changing any filenames.

If you need to submit multiple files, you can archive them in a .zip file. (No other format.)


In [ ]:
# This is a test cell. Please do not modify or delete.